### ISSUE TITLE
Fix Mapping for function names in substrait plans.

### ISSUE THREAD

**Issue by richtia** [duckdblabs/substrait#5]
It looks like duckdb doesn't have a mapping between the duckdb SQL function names to substrait function names when creating the substrait plans.  For the most part, the substrait plans function names are the same as the duckdb SQL function name.

Here's a list of functions that should have their names remapped when producing the substrait plans.  Expected substrait function name is in parenthesis.

- [ ] mod (modulus)
- [ ] sum (sum) - the function name in the substrait plan is sum_no_overflow
- [ ] abs (abs) - there don't seem to be any substrait functions generated in the plan for this function
- [ ] count (count) - the function name in the substrait plan is count_star
- [ ] stddev (std_dev)
- [ ] extract (extract) - extract using year `SELECT COL, extract('year' FROM COL)`.  the function name in the substrait plan is year
- [ ] like (like) - `SELECT N_NAME FROM nation.parquet WHERE N_NAME LIKE 'ALGERIA';` uses `and`, `equal`, and `is_not_null` substrait functions in the produced plan
- [ ] prefix (starts_with)
- [ ] suffix (ends_with)
- [ ] substr (substring)
- [ ] length (char_length)
- [ ] isnan (is_nan)
- [ ] isfinite (is_finite)
- [ ] isinf (is_infinite)

**Comment by LindsayWray** [comment]
> @LindsayWray Are we missing any of these? Is this good to close?

Yes, this can be closed. Only missing extract, but I've made a separate issue for that one #24
